# System Release Workflow

# Useful References:
#   - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#   - https://docs.github.com/en/actions/learn-github-actions/contexts
#   - https://docs.github.com/en/actions/learn-github-actions/environment-variables
#   - https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
#   - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#   - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

name: System Release Build

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build System
        uses: borales/actions-yarn@v4
        with:
          cmd: dist

      # Modify system.json with values specific to the release.
      - name: Modify System Manifest
        id: sub_manifest_link_version
        uses: cschleiden/replace-tokens@v1
        with:
          files: "./dist/system.json"
        env:
          MANIFEST: "https://github.com/${{github.repository}}/releases/latest/download/system.json"
          DOWNLOAD: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip"

      # Create a "system.zip" archive containing all the system's required files.
      - name: Create System Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: system.zip
          directory: dist

      # Update the GitHub release with the manifest and system archive files.
      - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/system.json, ./dist/system.zip"
          allowUpdates: true
          name: ${{ github.event.release.name }}
          # draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
